apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegram-ai-agent.componentName" (dict "ctx" . "name" "backend-config") }}
  labels:
    {{- include "telegram-ai-agent.componentLabels" (dict "ctx" . "name" "backend") | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
