{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telegram-ai-agent.backend.serviceAccountName" . }}
  labels:
    {{- include "telegram-ai-agent.componentLabels" (dict "ctx" . "name" "backend") | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
